export interface Product {
  reviews: number;
  id: string;
  slug: string;
  name: string;
  category: "hair" | "nails" | "accessories";
  subcategory: string;
  price: number;
  originalPrice?: number;
  images: string[];
  rating: number;
  reviewCount: number;
  inStock: boolean;
  stockCount: number;
  tags: string[];
  description: string;
  details: string[];
  isNew: boolean;
  isBestseller: boolean;
  isSale: boolean;
  careInstructions?: string;
  shadeOptions?: string[];
  lengthOptions?: string[];
}

const img = (query: string) =>
  `https://source.unsplash.com/600x600/?${query}`;

export const products: Product[] = [
  // ================= HAIR =================
  {
    id: "hair-1",
    slug: "brazilian-straight-hair-bundle-18",
    name: 'Brazilian Straight Hair Bundle (18")',
    category: "hair",
    subcategory: "Bundles",
    price: 45000,
    originalPrice: 50000,
    images: [img("straight hair weave"), img("hair bundle")],
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    stockCount: 30,
    tags: ["luxury", "straight", "brazilian"],
    description: "Premium Brazilian straight hair with natural shine.",
    details: ["100% human hair", "Double weft", "Tangle-free"],
    isNew: true,
    isBestseller: true,
    isSale: true,
    lengthOptions: ['18"', '20"', '22"'],
    careInstructions: "Use sulfate-free shampoo.",
    reviews: 124
  },

  {
    id: "hair-2",
    slug: "kinky-curly-closure-4x4",
    name: "Kinky Curly Closure 4x4",
    category: "hair",
    subcategory: "Closures",
    price: 28500,
    images: [img("curly hair closure")],
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    stockCount: 18,
    tags: ["curly", "closure"],
    description: "Soft kinky curls with natural density.",
    details: ["Swiss lace", "Pre-plucked hairline"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    lengthOptions: ['14"', '16"'],
    reviews: 89
  },

   {
    id: "hair-3",
    slug: "hd-lace-frontal-13x4",
    name: "HD Lace Frontal 13x4",
    category: "hair",
    subcategory: "Frontals",
    price: 62000,
    images: [img("lace-frontal")],
    rating: 4.9,
    reviewCount: 45,
    inStock: true,
    stockCount: 12,
    tags: ["HD lace", "invisible", "frontal"],
    description: "Ultra-thin HD lace for a seamless blend with any skin tone.",
    details: ["13x4 ear-to-ear coverage", "Transparent lace", "Small knots"],
    isNew: true,
    isBestseller: false,
    isSale: false,
    reviews: 45
  },
  {
    id: "hair-4",
    slug: "deep-wave-full-lace-wig",
    name: "Deep Wave Full Lace Wig",
    category: "hair",
    subcategory: "Wigs",
    price: 95000,
    originalPrice: 110000,
    images: [img("curly-wig")],
    rating: 5.0,
    reviewCount: 32,
    inStock: true,
    stockCount: 5,
    tags: ["wig", "full lace", "deep wave"],
    description: "Luxurious full lace wig that allows for versatile parting.",
    details: ["180% density", "Adjustable straps", "100% Remy hair"],
    isNew: false,
    isBestseller: true,
    isSale: true,
    reviews: 32
  },
  {
    id: "hair-5",
    slug: "bone-straight-bundle-20",
    name: 'Bone Straight Hair Bundle (20")',
    category: "hair",
    subcategory: "Bundles",
    price: 52000,
    images: [img("sleek-straight-hair")],
    rating: 4.7,
    reviewCount: 210,
    inStock: true,
    stockCount: 40,
    tags: ["bone straight", "sleek"],
    description: "Silky bone straight hair that requires minimal styling.",
    details: ["Can be dyed", "Double drawn", "Heat resistant"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    lengthOptions: ['20"', '22"', '24"'],
    reviews: 210
  },
  {
    id: "hair-6",
    slug: "jerry-curl-weave-bundle",
    name: "Jerry Curl Weave Bundle",
    category: "hair",
    subcategory: "Bundles",
    price: 38000,
    images: [img("jerry-curl-hair")],
    rating: 4.4,
    reviewCount: 76,
    inStock: true,
    stockCount: 22,
    tags: ["jerry curl", "bouncy"],
    description: "Classic bouncy curls with a healthy luster.",
    details: ["Minimal shedding", "Soft texture"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 76
  },
  {
    id: "hair-7",
    slug: "raw-indian-hair-extension",
    name: "Raw Indian Hair Extension",
    category: "hair",
    subcategory: "Extensions",
    price: 41000,
    images: [img("raw-hair")],
    rating: 4.9,
    reviewCount: 54,
    inStock: true,
    stockCount: 15,
    tags: ["raw hair", "unprocessed", "indian"],
    description: "Single donor raw Indian hair with natural waves.",
    details: ["Unprocessed", "Lasts up to 3 years", "Natural color"],
    isNew: true,
    isBestseller: false,
    isSale: false,
    reviews: 54
  },
  {
    id: "hair-8",
    slug: "silk-press-heat-protectant",
    name: "Silk Press Heat Protectant",
    category: "hair",
    subcategory: "Care",
    price: 8500,
    images: [img("hair-spray-bottle")],
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    stockCount: 50,
    tags: ["heat protection", "silk press"],
    description: "Protects strands from high heat while adding shine.",
    details: ["Up to 450°F protection", "Non-greasy"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    reviews: 156
  },
  {
    id: "hair-9",
    slug: "curl-defining-cream",
    name: "Curl Defining Cream",
    category: "hair",
    subcategory: "Care",
    price: 6200,
    images: [img("hair-cream")],
    rating: 4.3,
    reviewCount: 92,
    inStock: true,
    stockCount: 35,
    tags: ["curls", "styling"],
    description: "Enhances your natural curl pattern without the crunch.",
    details: ["Shea butter infused", "Anti-frizz"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 92
  },
  {
    id: "hair-10",
    slug: "deep-conditioning-mask",
    name: "Deep Conditioning Mask",
    category: "hair",
    subcategory: "Care",
    price: 7800,
    images: [img("hair-mask")],
    rating: 4.7,
    reviewCount: 118,
    inStock: true,
    stockCount: 28,
    tags: ["repair", "moisture"],
    description: "Intensive treatment for damaged or dry hair.",
    details: ["Keratin enriched", "15-minute treatment"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 118
  },
  {
    id: "hair-11",
    slug: "scalp-serum-growth",
    name: "Scalp Serum (Growth Formula)",
    category: "hair",
    subcategory: "Care",
    price: 12500,
    images: [img("serum-bottle")],
    rating: 4.6,
    reviewCount: 64,
    inStock: true,
    stockCount: 20,
    tags: ["growth", "scalp care"],
    description: "Stimulates follicles for thicker, longer hair.",
    details: ["Biotin & Caffeine", "Cruelty-free"],
    isNew: true,
    isBestseller: false,
    isSale: false,
    reviews: 64
  },
  {
    id: "hair-12",
    slug: "satin-lined-bonnet-luxury",
    name: "Satin-Lined Bonnet (Luxury)",
    category: "hair",
    subcategory: "Protection",
    price: 4500,
    images: [img("hair-bonnet")],
    rating: 4.9,
    reviewCount: 340,
    inStock: true,
    stockCount: 45,
    tags: ["satin", "night-wear"],
    description: "Protects edges and styles overnight.",
    details: ["Extra large", "Adjustable band"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    reviews: 340
  },

  // ================= NAILS (10 ITEMS) =================
  {
    id: "nails-1",
    slug: "gel-nail-kit-complete",
    name: "Gel Nail Kit (Complete Set)",
    category: "nails",
    subcategory: "Kits",
    price: 22000,
    originalPrice: 25000,
    images: [img("nail-kit")],
    rating: 4.8,
    reviewCount: 88,
    inStock: true,
    stockCount: 15,
    tags: ["DIY", "complete set"],
    description: "Everything you need for a salon-quality gel mani at home.",
    details: ["Includes Lamp", "Top & Base coat included"],
    isNew: true,
    isBestseller: true,
    isSale: true,
    reviews: 88
  },
  {
    id: "nails-2",
    slug: "press-on-nails-french-tips",
    name: "Press-On Nails — French Tips (24pc)",
    category: "nails",
    subcategory: "Press-ons",
    price: 5500,
    images: [img("french-manicure")],
    rating: 4.5,
    reviewCount: 210,
    inStock: true,
    stockCount: 50,
    tags: ["classic", "french tip"],
    description: "Classic white French tips for an elegant look.",
    details: ["24 nails", "Glue included", "Reusable"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    reviews: 210
  },
  {
    id: "nails-3",
    slug: "press-on-nails-nude-ombre",
    name: "Press-On Nails — Nude Ombre (24pc)",
    category: "nails",
    subcategory: "Press-ons",
    price: 5500,
    images: [img("ombre-nails")],
    rating: 4.6,
    reviewCount: 145,
    inStock: true,
    stockCount: 30,
    tags: ["ombre", "nude"],
    description: "Seamless nude-to-white gradient nails.",
    details: ["Medium Coffin shape", "Glossy finish"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 145
  },
  {
    id: "nails-4",
    slug: "press-on-nails-floral-art",
    name: "Press-On Nails — Floral Art (24pc)",
    category: "nails",
    subcategory: "Press-ons",
    price: 6500,
    images: [img("floral-nails")],
    rating: 4.7,
    reviewCount: 67,
    inStock: true,
    stockCount: 25,
    tags: ["floral", "artistic"],
    description: "Hand-painted floral designs for a boutique feel.",
    details: ["Unique design", "Custom lengths"],
    isNew: true,
    isBestseller: false,
    isSale: false,
    reviews: 67
  },
  {
    id: "nails-5",
    slug: "nail-lamp-uv-led",
    name: "Nail Lamp UV/LED (36W)",
    category: "nails",
    subcategory: "Tools",
    price: 18500,
    images: [img("nail-uv-lamp")],
    rating: 4.8,
    reviewCount: 112,
    inStock: true,
    stockCount: 10,
    tags: ["lamp", "pro tool"],
    description: "Dual light source for fast curing of all gel types.",
    details: ["36W power", "Auto-sensor", "LCD display"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    reviews: 112
  },
  {
    id: "nails-6",
    slug: "gel-polish-collection-12",
    name: "Gel Polish Collection (12 colours)",
    category: "nails",
    subcategory: "Polish",
    price: 15000,
    images: [img("nail-polish-set")],
    rating: 4.4,
    reviewCount: 53,
    inStock: true,
    stockCount: 20,
    tags: ["gel", "collection"],
    description: "A curation of 12 best-selling seasonal colors.",
    details: ["Highly pigmented", "3-week wear"],
    isNew: true,
    isBestseller: false,
    isSale: false,
    shadeOptions: ["Pastel Mix", "Nude Essentials", "Neon Vibes"],
    reviews: 53
  },
  {
    id: "nails-7",
    slug: "nail-drill-machine-pro",
    name: "Nail Drill Machine (Pro)",
    category: "nails",
    subcategory: "Tools",
    price: 32000,
    images: [img("nail-drill")],
    rating: 4.9,
    reviewCount: 28,
    inStock: true,
    stockCount: 8,
    tags: ["e-file", "pro"],
    description: "High-speed professional nail drill for removal and shaping.",
    details: ["35,000 RPM", "Quiet motor", "Rechargeable"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 28
  },
  {
    id: "nails-8",
    slug: "cuticle-oil-serum",
    name: "Cuticle Oil Serum",
    category: "nails",
    subcategory: "Care",
    price: 3800,
    images: [img("oil-dropper")],
    rating: 4.6,
    reviewCount: 198,
    inStock: true,
    stockCount: 50,
    tags: ["hydration", "cuticle care"],
    description: "Nourishes and repairs dry cuticles with vitamin E.",
    details: ["Jojoba oil based", "Dropper application"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    reviews: 198
  },
  {
    id: "nails-9",
    slug: "nail-art-brush-set",
    name: "Nail Art Brush Set (12pc)",
    category: "nails",
    subcategory: "Tools",
    price: 7200,
    images: [img("fine-brushes")],
    rating: 4.2,
    reviewCount: 41,
    inStock: true,
    stockCount: 35,
    tags: ["nail art", "DIY"],
    description: "Ultra-fine brushes for detailing and striping.",
    details: ["Synthetic bristles", "12 different tips"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 41
  },
  {
    id: "nails-10",
    slug: "acrylic-powder-kit",
    name: "Acrylic Powder Kit",
    category: "nails",
    subcategory: "Tools",
    price: 19500,
    images: [img("powder-jars")],
    rating: 4.5,
    reviewCount: 37,
    inStock: true,
    stockCount: 14,
    tags: ["acrylic", "extensions"],
    description: "Fine-milled acrylic powder for sturdy nail extensions.",
    details: ["Pink, White, Clear", "Bubble-free formula"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 37
  },

  // ================= ACCESSORIES (10 ITEMS) =================
  {
    id: "acc-1",
    slug: "silk-pillowcase-queen",
    name: "Silk Pillowcase (Queen Size)",
    category: "accessories",
    subcategory: "Lifestyle",
    price: 9500,
    images: [img("silk-pillowcase")],
    rating: 4.9,
    reviewCount: 220,
    inStock: true,
    stockCount: 40,
    tags: ["silk", "anti-aging"],
    description: "Sleep on silk to prevent hair tangles and skin creases.",
    details: ["100% Mulberry Silk", "Hidden zipper"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    reviews: 220
  },
  {
    id: "acc-2",
    slug: "jade-roller-gua-sha",
    name: "Jade Roller & Gua Sha Set",
    category: "accessories",
    subcategory: "Skincare",
    price: 12000,
    images: [img("jade-roller")],
    rating: 4.7,
    reviewCount: 85,
    inStock: true,
    stockCount: 25,
    tags: ["facial", "detox"],
    description: "Natural stone tools for facial massage and lymphatic drainage.",
    details: ["Authentic Jade", "Storage box included"],
    isNew: true,
    isBestseller: false,
    isSale: false,
    reviews: 85
  },
  {
    id: "acc-3",
    slug: "vanity-mirror-lights",
    name: "Vanity Mirror with Lights",
    category: "accessories",
    subcategory: "Lifestyle",
    price: 35000,
    originalPrice: 40000,
    images: [img("vanity-mirror")],
    rating: 5.0,
    reviewCount: 15,
    inStock: true,
    stockCount: 6,
    tags: ["makeup", "LED"],
    description: "Studio-quality lighting for your makeup routine.",
    details: ["Touch dimming", "USB powered", "10x magnification"],
    isNew: true,
    isBestseller: false,
    isSale: true,
    reviews: 15
  },
  {
    id: "acc-4",
    slug: "makeup-brush-set-24",
    name: "Makeup Brush Set (24pc)",
    category: "accessories",
    subcategory: "Tools",
    price: 18000,
    images: [img("makeup-brushes")],
    rating: 4.6,
    reviewCount: 134,
    inStock: true,
    stockCount: 30,
    tags: ["brushes", "full set"],
    description: "A comprehensive set for face, eyes, and lips.",
    details: ["Soft synthetic hair", "Travel pouch included"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    reviews: 134
  },
  {
    id: "acc-5",
    slug: "perfume-atomiser-gold",
    name: "Perfume Atomiser (Gold)",
    category: "accessories",
    subcategory: "Travel",
    price: 4200,
    images: [img("small-bottle")],
    rating: 4.4,
    reviewCount: 58,
    inStock: true,
    stockCount: 50,
    tags: ["travel size", "gold"],
    description: "Refillable mini perfume bottle for your handbag.",
    details: ["5ml capacity", "Leak-proof"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 58
  },
  {
    id: "acc-6",
    slug: "eyelash-extension-kit",
    name: "Eyelash Extension Kit",
    category: "accessories",
    subcategory: "Tools",
    price: 14500,
    images: [img("lashes-kit")],
    rating: 4.3,
    reviewCount: 42,
    inStock: true,
    stockCount: 18,
    tags: ["lashes", "extension"],
    description: "Starter kit for DIY individual lash extensions.",
    details: ["Tweezers & Glue", "Mink-style lashes"],
    isNew: true,
    isBestseller: false,
    isSale: false,
    reviews: 42
  },
  {
    id: "acc-7",
    slug: "hair-steamer-tabletop",
    name: "Hair Steamer (Tabletop)",
    category: "accessories",
    subcategory: "Salon Tools",
    price: 55000,
    images: [img("steamer")],
    rating: 4.9,
    reviewCount: 22,
    inStock: true,
    stockCount: 4,
    tags: ["hair care", "spa"],
    description: "Ozone steamer for deep conditioning and scalp health.",
    details: ["Adjustable mist", "Safety auto-off"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 22
  },
  {
    id: "acc-8",
    slug: "detangling-shower-brush",
    name: "Detangling Shower Brush",
    category: "accessories",
    subcategory: "Tools",
    price: 3500,
    images: [img("hair-brush")],
    rating: 4.8,
    reviewCount: 280,
    inStock: true,
    stockCount: 50,
    tags: ["detangle", "shower"],
    description: "Gently detangles wet hair without breakage.",
    details: ["Ergonomic grip", "Flexible bristles"],
    isNew: false,
    isBestseller: true,
    isSale: false,
    reviews: 280
  },
  {
    id: "acc-9",
    slug: "satin-hair-scrunchie-set",
    name: "Satin Hair Scrunchie Set (6pc)",
    category: "accessories",
    subcategory: "Hair Care",
    price: 2800,
    images: [img("scrunchies")],
    rating: 4.5,
    reviewCount: 165,
    inStock: true,
    stockCount: 45,
    tags: ["scrunchies", "no-crease"],
    description: "Pack of 6 luxurious satin scrunchies.",
    details: ["Assorted colors", "Gentle on hair"],
    isNew: false,
    isBestseller: false,
    isSale: false,
    reviews: 165
  },
  {
    id: "acc-10",
    slug: "magnetic-lashes-3pairs",
    name: "Magnetic Lashes (3 pairs)",
    category: "accessories",
    subcategory: "Lashes",
    price: 8000,
    images: [img("magnetic-lashes")],
    rating: 4.1,
    reviewCount: 74,
    inStock: true,
    stockCount: 20,
    tags: ["magnetic", "no-glue"],
    description: "No glue required. Snap on these magnetic lashes in seconds.",
    details: ["Includes magnetic liner", "Reusable 30+ times"],
    isNew: true,
    isBestseller: false,
    isSale: false,
    reviews: 74
  },

];