export interface Review {
  id: string;
  productSlug: string;
  name: string;
  rating: number;
  comment: string;
  date: string;
  verified: boolean;
  hasImage: boolean;
}

export const reviews: Review[] = [
  {
    id: "rev-1",
    productSlug: "brazilian-straight-hair-bundle-18",
    name: "Chioma Okafor",
    rating: 5,
    comment:
      "The hair is extremely soft and silky. No shedding at all. I’m obsessed!",
    date: "2025-01-12",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-2",
    productSlug: "brazilian-straight-hair-bundle-18",
    name: "Temitope Adebayo",
    rating: 4.5,
    comment:
      "Delivery was fast and quality exceeded my expectations.",
    date: "2025-01-05",
    verified: true,
    hasImage: false,
  },

  {
    id: "rev-3",
    productSlug: "hd-lace-frontal-13x4",
    name: "Ifunanya Okeke",
    rating: 5,
    comment: "The HD lace is literal magic. It melted into my skin so well, you can't even see the grid!",
    date: "2025-01-20",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-4",
    productSlug: "gel-nail-kit-complete",
    name: "Tolu Balogun",
    rating: 4.8,
    comment: "The lamp cures really fast. Only wish the kit came with more color options, but the quality is 10/10.",
    date: "2025-01-22",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-5",
    productSlug: "deep-wave-full-lace-wig",
    name: "Amaka Ibe",
    rating: 5,
    comment: "This wig is thick and luscious! I've washed it twice and the curls still pop perfectly.",
    date: "2025-01-25",
    verified: true,
    hasImage: false,
  },
  {
    id: "rev-6",
    productSlug: "satin-lined-bonnet-luxury",
    name: "Nneka Nwosu",
    rating: 4.5,
    comment: "Stays on my head all night and the satin is very high quality. My edges are happy.",
    date: "2025-01-28",
    verified: true,
    hasImage: false,
  },
  {
    id: "rev-7",
    productSlug: "press-on-nails-french-tips",
    name: "Sade Tinubu",
    rating: 5,
    comment: "Saved me a trip to the salon. They look exactly like acrylics and the glue is very strong.",
    date: "2025-02-01",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-8",
    productSlug: "curl-defining-cream",
    name: "Kemi Adesina",
    rating: 4.0,
    comment: "Smells amazing! Works great on my 4C hair, though I have to use a lot for my thick density.",
    date: "2025-02-03",
    verified: true,
    hasImage: false,
  },
  {
    id: "rev-9",
    productSlug: "scalp-serum-growth",
    name: "Zainab Ahmed",
    rating: 5,
    comment: "I've been using this for a month on my edges and I'm already seeing new growth. Highly recommend!",
    date: "2025-02-05",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-10",
    productSlug: "vanity-mirror-lights",
    name: "Adaeze Egwu",
    rating: 5,
    comment: "The lighting is so bright! It has transformed my makeup game. Best purchase this year.",
    date: "2025-02-07",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-11",
    productSlug: "bone-straight-bundle-20",
    name: "Halima Yusuf",
    rating: 4.7,
    comment: "Truly bone straight. I didn't even need to flat iron it out of the pack.",
    date: "2025-02-10",
    verified: true,
    hasImage: false,
  },
  {
    id: "rev-12",
    productSlug: "nail-drill-machine-pro",
    name: "Uche Bakare",
    rating: 5,
    comment: "Very quiet and professional. It doesn't vibrate much, which makes it easy to control.",
    date: "2025-02-12",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-13",
    productSlug: "silk-pillowcase-queen",
    name: "Ifunanya Okeke",
    rating: 4.5,
    comment: "So soft and cooling. My hair isn't nearly as frizzy in the morning.",
    date: "2025-02-14",
    verified: true,
    hasImage: false,
  },
  {
    id: "rev-14",
    productSlug: "makeup-brush-set-24",
    name: "Tolu Balogun",
    rating: 5,
    comment: "The bristles are so soft and they don't shed when I wash them. Great value.",
    date: "2025-02-15",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-15",
    productSlug: "jerry-curl-weave-bundle",
    name: "Amaka Ibe",
    rating: 4.2,
    comment: "Pretty hair, but you definitely need the curl cream to keep it looking fresh.",
    date: "2025-02-16",
    verified: true,
    hasImage: false,
  },
  {
    id: "rev-16",
    productSlug: "hair-steamer-tabletop",
    name: "Nneka Nwosu",
    rating: 5,
    comment: "A life saver for my deep conditioning days. My hair feels so hydrated now.",
    date: "2025-02-17",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-17",
    productSlug: "magnetic-lashes-3pairs",
    name: "Sade Tinubu",
    rating: 4.0,
    comment: "Took me a few tries to get the liner right, but once they're on, they don't budge!",
    date: "2025-02-18",
    verified: true,
    hasImage: false,
  },
  {
    id: "rev-18",
    productSlug: "jade-roller-gua-sha",
    name: "Kemi Adesina",
    rating: 5,
    comment: "Feels so luxury on the skin, especially when kept in the fridge. Love it.",
    date: "2025-02-19",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-19",
    productSlug: "press-on-nails-floral-art",
    name: "Zainab Ahmed",
    rating: 4.9,
    comment: "Got so many compliments on these! Everyone thought I went to a high-end salon.",
    date: "2025-02-20",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-20",
    productSlug: "silk-press-heat-protectant",
    name: "Adaeze Egwu",
    rating: 5,
    comment: "Left my hair smelling good and very shiny. No heat damage detected!",
    date: "2025-02-21",
    verified: true,
    hasImage: false,
  },
  {
    id: "rev-21",
    productSlug: "raw-indian-hair-extension",
    name: "Halima Yusuf",
    rating: 5,
    comment: "The quality of this raw hair is unmatched. You can tell it's high grade.",
    date: "2025-02-21",
    verified: true,
    hasImage: true,
  },
  {
    id: "rev-22",
    productSlug: "detangling-shower-brush",
    name: "Uche Bakare",
    rating: 4.6,
    comment: "Glides through knots easily. Much better than my old wide-tooth comb.",
    date: "2025-02-22",
    verified: true,
    hasImage: false,
  },
];